[package]
name = "not-byte-auth-api"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "api"
path = "src/main.rs"

[dependencies]
axum = "0.8.8"
# blake3 = "1.8.3"
# faker_rand = "0.1.1"
# rand = "0.8.5"
# serde = { version = "1.0.2", features = ["derive"] }
# serde_json = "1.0.0"
# surrealdb = "2.4.1"
# thiserror = "2.0.18"
tokio = { version = "1.0.0", features = ["full"] }
# tower-http = { version = "0.6.8", features = ["cors"] }
