[package]
name = "oauth-api"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "oauth-api"
path = "src/main.rs"

[dependencies]
axum =    { version = "0.8.8",  features = ["json"] }
serde =   { version = "1.0.2",  features = ["derive"] }
scylla =  { version = "1.5",    features = [] }
tokio =   { version = "1.12",   features = ["full"] }
futures = { version = "0.3.32", features = [] }
uuid =    { version = "1.21.0", features = ["serde", "v7"] }
